/*
# Description
This file has been generated by chatgpt, adjustments have been added by the author
*/

const fs = require('fs');

// The starting and ending day numbers
const startDay = 6;
const endDay = 25;

// The number of digits to pad the day numbers with
const padLength = 2;

// The character to use for padding (a zero)
const padCharacter = '0';

// The content to write to each file
const fileContent = day => `import fs from 'fs';

const input = fs.readFileSync(__dirname + '/../../day-${day}/input.txt', 'utf-8')

export const part1 = ''
export const part2 = ''`;

// Loop through the day numbers
for (let day = startDay; day <= endDay; day++) {
  // Pad the day number with leading zeros
  const paddedDay = day.toString().padStart(padLength, padCharacter);

  // Construct the path to the file
  const filePath = `day-${paddedDay}/index.ts`;

  // Write the content to the file
  fs.writeFileSync(filePath, fileContent(paddedDay));
}
